/*
 * Dinosaur Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Dinosaur service
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ScannerSpecAnalyzerScaling struct for ScannerSpecAnalyzerScaling
type ScannerSpecAnalyzerScaling struct {
	AutoScaling string `json:"autoScaling,omitempty"`
	Replicas    int32  `json:"replicas,omitempty"`
	MinReplicas int32  `json:"minReplicas,omitempty"`
	MaxReplicas int32  `json:"maxReplicas,omitempty"`
}
