/*
 * Red Hat Advanced Cluster Security Service Fleet Manager Admin API
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager Admin APIs that can be used by RHACS Managed Service Operations Team.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// CentralAllOfRoutes struct for CentralAllOfRoutes
type CentralAllOfRoutes struct {
	Domain string `json:"domain,omitempty"`
	Router string `json:"router,omitempty"`
}
