/*
 * Dinosaur Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Dinosaur service
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ScannerSpec struct for ScannerSpec
type ScannerSpec struct {
	Analyzer ScannerSpecAnalyzer `json:"analyzer,omitempty"`
	Db       ScannerSpecDb       `json:"db,omitempty"`
}
