run:
  skip-dirs:
    - internal/dinosaur/pkg/api/public
    - internal/dinosaur/pkg/api/private
    - internal/dinosaur/pkg/api/admin/private
    - pkg/client/redhatsso/api
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
    - path: pkg/client/fleetmanager/client.go # Ignore wrapcheck for the client, specifically within the RoundTripper.
      linters:
        - wrapcheck
    - linters:
        - revive
      text: "should have a package comment, unless it's in another file for this package"
    - linters:
        - revive
      text: "should not use dot imports"
    - linters:
        - revive
      text: "returns unexported type .* which can be annoying to use"
    - linters:
        - revive
      text: "error strings should not be capitalized or end with punctuation or a newline"
    - linters:
        - revive
      text: "should omit type int from declaration"
    - linters:
        - revive
      text: "don't use leading k in Go names"

linters-settings:
  gosec:
    includes:
    - G601
  revive:
    min-confidence: 0
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments: ["disableStutteringCheck"] #TODO(ROX-11892) enable revive naming checks
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - Print
          - Printf
          - Println
          - Debug
          - Debugf
          - Info
          - Infof
          - Warn
          - Warnf
          - Error
          - Errorf
  gocritic:
    enabled-checks:
      - commentFormatting
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  staticcheck:
    go: "1.17"
    checks: [ all,-ST1000,-ST1001,-ST1003,-ST1005,-SA1019,-SA4001,-ST1016 ]
  wrapcheck:
    # ignoreSigRegexps: uncomment to add ignore rules

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    - exportloopref
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    - goimports
    - revive
    # - gomnd
    # - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    # - nakedret
    # - nestif
    - nolintlint
    # - prealloc
    - rowserrcheck
    # - scopelint
    - staticcheck
    # - structcheck
    # - stylecheck
    # - testpackage
    # - typecheck
    # - unconvert
    # - unparam
    # - unused
    # - varcheck
    # - whitespace
    - wrapcheck
    # - wsl
