// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sso

import (
	"github.com/stackrox/acs-fleet-manager/pkg/api"
	"github.com/stackrox/acs-fleet-manager/pkg/client/iam"
	"github.com/stackrox/acs-fleet-manager/pkg/errors"
	"sync"
)

// Ensure, that IAMServiceMock does implement IAMService.
// If this is not the case, regenerate this file with moq.
var _ IAMService = &IAMServiceMock{}

// IAMServiceMock is a mock implementation of IAMService.
//
// 	func TestSomethingThatUsesIAMService(t *testing.T) {
//
// 		// make and configure a mocked IAMService
// 		mockedIAMService := &IAMServiceMock{
// 			DeRegisterAcsFleetshardOperatorServiceAccountFunc: func(agentClusterID string) *errors.ServiceError {
// 				panic("mock out the DeRegisterAcsFleetshardOperatorServiceAccount method")
// 			},
// 			GetConfigFunc: func() *iam.IAMConfig {
// 				panic("mock out the GetConfig method")
// 			},
// 			GetRealmConfigFunc: func() *iam.IAMRealmConfig {
// 				panic("mock out the GetRealmConfig method")
// 			},
// 			RegisterAcsFleetshardOperatorServiceAccountFunc: func(agentClusterID string) (*api.ServiceAccount, *errors.ServiceError) {
// 				panic("mock out the RegisterAcsFleetshardOperatorServiceAccount method")
// 			},
// 		}
//
// 		// use mockedIAMService in code that requires IAMService
// 		// and then make assertions.
//
// 	}
type IAMServiceMock struct {
	// DeRegisterAcsFleetshardOperatorServiceAccountFunc mocks the DeRegisterAcsFleetshardOperatorServiceAccount method.
	DeRegisterAcsFleetshardOperatorServiceAccountFunc func(agentClusterID string) *errors.ServiceError

	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func() *iam.IAMConfig

	// GetRealmConfigFunc mocks the GetRealmConfig method.
	GetRealmConfigFunc func() *iam.IAMRealmConfig

	// RegisterAcsFleetshardOperatorServiceAccountFunc mocks the RegisterAcsFleetshardOperatorServiceAccount method.
	RegisterAcsFleetshardOperatorServiceAccountFunc func(agentClusterID string) (*api.ServiceAccount, *errors.ServiceError)

	// calls tracks calls to the methods.
	calls struct {
		// DeRegisterAcsFleetshardOperatorServiceAccount holds details about calls to the DeRegisterAcsFleetshardOperatorServiceAccount method.
		DeRegisterAcsFleetshardOperatorServiceAccount []struct {
			// AgentClusterID is the agentClusterID argument value.
			AgentClusterID string
		}
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
		}
		// GetRealmConfig holds details about calls to the GetRealmConfig method.
		GetRealmConfig []struct {
		}
		// RegisterAcsFleetshardOperatorServiceAccount holds details about calls to the RegisterAcsFleetshardOperatorServiceAccount method.
		RegisterAcsFleetshardOperatorServiceAccount []struct {
			// AgentClusterID is the agentClusterID argument value.
			AgentClusterID string
		}
	}
	lockDeRegisterAcsFleetshardOperatorServiceAccount sync.RWMutex
	lockGetConfig                                     sync.RWMutex
	lockGetRealmConfig                                sync.RWMutex
	lockRegisterAcsFleetshardOperatorServiceAccount   sync.RWMutex
}

// DeRegisterAcsFleetshardOperatorServiceAccount calls DeRegisterAcsFleetshardOperatorServiceAccountFunc.
func (mock *IAMServiceMock) DeRegisterAcsFleetshardOperatorServiceAccount(agentClusterID string) *errors.ServiceError {
	if mock.DeRegisterAcsFleetshardOperatorServiceAccountFunc == nil {
		panic("IAMServiceMock.DeRegisterAcsFleetshardOperatorServiceAccountFunc: method is nil but IAMService.DeRegisterAcsFleetshardOperatorServiceAccount was just called")
	}
	callInfo := struct {
		AgentClusterID string
	}{
		AgentClusterID: agentClusterID,
	}
	mock.lockDeRegisterAcsFleetshardOperatorServiceAccount.Lock()
	mock.calls.DeRegisterAcsFleetshardOperatorServiceAccount = append(mock.calls.DeRegisterAcsFleetshardOperatorServiceAccount, callInfo)
	mock.lockDeRegisterAcsFleetshardOperatorServiceAccount.Unlock()
	return mock.DeRegisterAcsFleetshardOperatorServiceAccountFunc(agentClusterID)
}

// DeRegisterAcsFleetshardOperatorServiceAccountCalls gets all the calls that were made to DeRegisterAcsFleetshardOperatorServiceAccount.
// Check the length with:
//     len(mockedIAMService.DeRegisterAcsFleetshardOperatorServiceAccountCalls())
func (mock *IAMServiceMock) DeRegisterAcsFleetshardOperatorServiceAccountCalls() []struct {
	AgentClusterID string
} {
	var calls []struct {
		AgentClusterID string
	}
	mock.lockDeRegisterAcsFleetshardOperatorServiceAccount.RLock()
	calls = mock.calls.DeRegisterAcsFleetshardOperatorServiceAccount
	mock.lockDeRegisterAcsFleetshardOperatorServiceAccount.RUnlock()
	return calls
}

// GetConfig calls GetConfigFunc.
func (mock *IAMServiceMock) GetConfig() *iam.IAMConfig {
	if mock.GetConfigFunc == nil {
		panic("IAMServiceMock.GetConfigFunc: method is nil but IAMService.GetConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc()
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//     len(mockedIAMService.GetConfigCalls())
func (mock *IAMServiceMock) GetConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}

// GetRealmConfig calls GetRealmConfigFunc.
func (mock *IAMServiceMock) GetRealmConfig() *iam.IAMRealmConfig {
	if mock.GetRealmConfigFunc == nil {
		panic("IAMServiceMock.GetRealmConfigFunc: method is nil but IAMService.GetRealmConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetRealmConfig.Lock()
	mock.calls.GetRealmConfig = append(mock.calls.GetRealmConfig, callInfo)
	mock.lockGetRealmConfig.Unlock()
	return mock.GetRealmConfigFunc()
}

// GetRealmConfigCalls gets all the calls that were made to GetRealmConfig.
// Check the length with:
//     len(mockedIAMService.GetRealmConfigCalls())
func (mock *IAMServiceMock) GetRealmConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetRealmConfig.RLock()
	calls = mock.calls.GetRealmConfig
	mock.lockGetRealmConfig.RUnlock()
	return calls
}

// RegisterAcsFleetshardOperatorServiceAccount calls RegisterAcsFleetshardOperatorServiceAccountFunc.
func (mock *IAMServiceMock) RegisterAcsFleetshardOperatorServiceAccount(agentClusterID string) (*api.ServiceAccount, *errors.ServiceError) {
	if mock.RegisterAcsFleetshardOperatorServiceAccountFunc == nil {
		panic("IAMServiceMock.RegisterAcsFleetshardOperatorServiceAccountFunc: method is nil but IAMService.RegisterAcsFleetshardOperatorServiceAccount was just called")
	}
	callInfo := struct {
		AgentClusterID string
	}{
		AgentClusterID: agentClusterID,
	}
	mock.lockRegisterAcsFleetshardOperatorServiceAccount.Lock()
	mock.calls.RegisterAcsFleetshardOperatorServiceAccount = append(mock.calls.RegisterAcsFleetshardOperatorServiceAccount, callInfo)
	mock.lockRegisterAcsFleetshardOperatorServiceAccount.Unlock()
	return mock.RegisterAcsFleetshardOperatorServiceAccountFunc(agentClusterID)
}

// RegisterAcsFleetshardOperatorServiceAccountCalls gets all the calls that were made to RegisterAcsFleetshardOperatorServiceAccount.
// Check the length with:
//     len(mockedIAMService.RegisterAcsFleetshardOperatorServiceAccountCalls())
func (mock *IAMServiceMock) RegisterAcsFleetshardOperatorServiceAccountCalls() []struct {
	AgentClusterID string
} {
	var calls []struct {
		AgentClusterID string
	}
	mock.lockRegisterAcsFleetshardOperatorServiceAccount.RLock()
	calls = mock.calls.RegisterAcsFleetshardOperatorServiceAccount
	mock.lockRegisterAcsFleetshardOperatorServiceAccount.RUnlock()
	return calls
}
