/*
 * sso.redhat.com API documentation
 *
 * This is the API documentation for sso.redhat.com
 *
 * API version: 5.0.19-SNAPSHOT
 * Contact: it-user-team-list@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package api

// Error struct for Error
type Error struct {
	// The cause of the Error.
	Error string `json:"error"`
}
