/*
 * sso.redhat.com API documentation
 *
 * This is the API documentation for sso.redhat.com
 *
 * API version: 5.0.19-SNAPSHOT
 * Contact: it-user-team-list@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package api

// AcsClientResponseData struct for AcsClientResponseData
type AcsClientResponseData struct {
	ClientId  string `json:"clientId,omitempty"`
	Secret    string `json:"secret,omitempty"`
	Name      string `json:"name,omitempty"`
	CreatedAt int64  `json:"createdAt,omitempty"`
}
