// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"github.com/stackrox/acs-fleet-manager/internal/dinosaur/pkg/api/dbapi"
	"github.com/stackrox/acs-fleet-manager/pkg/api"
	"sync"
)

// Ensure, that ClusterPlacementStrategyMock does implement ClusterPlacementStrategy.
// If this is not the case, regenerate this file with moq.
var _ ClusterPlacementStrategy = &ClusterPlacementStrategyMock{}

// ClusterPlacementStrategyMock is a mock implementation of ClusterPlacementStrategy.
//
// 	func TestSomethingThatUsesClusterPlacementStrategy(t *testing.T) {
//
// 		// make and configure a mocked ClusterPlacementStrategy
// 		mockedClusterPlacementStrategy := &ClusterPlacementStrategyMock{
// 			FindClusterFunc: func(dinosaur *dbapi.CentralRequest) (*api.Cluster, error) {
// 				panic("mock out the FindCluster method")
// 			},
// 		}
//
// 		// use mockedClusterPlacementStrategy in code that requires ClusterPlacementStrategy
// 		// and then make assertions.
//
// 	}
type ClusterPlacementStrategyMock struct {
	// FindClusterFunc mocks the FindCluster method.
	FindClusterFunc func(dinosaur *dbapi.CentralRequest) (*api.Cluster, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindCluster holds details about calls to the FindCluster method.
		FindCluster []struct {
			// Dinosaur is the dinosaur argument value.
			Dinosaur *dbapi.CentralRequest
		}
	}
	lockFindCluster sync.RWMutex
}

// FindCluster calls FindClusterFunc.
func (mock *ClusterPlacementStrategyMock) FindCluster(dinosaur *dbapi.CentralRequest) (*api.Cluster, error) {
	if mock.FindClusterFunc == nil {
		panic("ClusterPlacementStrategyMock.FindClusterFunc: method is nil but ClusterPlacementStrategy.FindCluster was just called")
	}
	callInfo := struct {
		Dinosaur *dbapi.CentralRequest
	}{
		Dinosaur: dinosaur,
	}
	mock.lockFindCluster.Lock()
	mock.calls.FindCluster = append(mock.calls.FindCluster, callInfo)
	mock.lockFindCluster.Unlock()
	return mock.FindClusterFunc(dinosaur)
}

// FindClusterCalls gets all the calls that were made to FindCluster.
// Check the length with:
//     len(mockedClusterPlacementStrategy.FindClusterCalls())
func (mock *ClusterPlacementStrategyMock) FindClusterCalls() []struct {
	Dinosaur *dbapi.CentralRequest
} {
	var calls []struct {
		Dinosaur *dbapi.CentralRequest
	}
	mock.lockFindCluster.RLock()
	calls = mock.calls.FindCluster
	mock.lockFindCluster.RUnlock()
	return calls
}
