#!/usr/bin/env bash

## This script assembles ImagePullSecrets for Quay.io as Kubernetes manifests ready for applying them to a cluster.

GITROOT="$(git rev-parse --show-toplevel)"
export GITROOT
# shellcheck source=/dev/null
source "${GITROOT}/dev/env/scripts/lib.sh"
init

registry="quay.io"
username="${QUAY_USER:-}"
password="${QUAY_TOKEN:-}"

if type openssl >/dev/null 2>&1; then
    b64enc_cmd=(openssl base64)
elif type base64 >/dev/null 2>&1; then
    b64enc_cmd=(base64)
else
    echo "No base64 command was found on your system!" 1>&2
    exit 1
fi

if ! "${b64enc_cmd[@]}" </dev/null >/dev/null 2>&1; then
    echo >&2 "${b64enc_cmd[*]} command fails to encode an empty string!"
    exit 1
fi

if [[ -z "${username}" ]]; then
    echo -n "Enter quay.io username: "
    read -r username
fi

if [[ -z "${password}" ]]; then
    echo -n "Enter quay.io password: "
    read -r -s password
fi

function b64enc() {
    echo -n "$1" | "${b64enc_cmd[@]}" | tr -d '\n'
}

function url2std() {
    tr '_-' '/+' | tr -d '\n'
}

function std2url() {
    tr '/+' '_-' | tr -d '\n'
}

function mkauth() {
    local username="$1"
    local password="$2"

    b64enc "${username}:${password}" | std2url
    return $?
}

function print_auth() {
    local auth_token="$1"
    if [[ -z $auth_token ]]; then
        return 1
    fi
    local auth_token_std
    auth_token_std=$(url2std <<<"$auth_token")
    local auths_str="{\"auths\":{\"$registry\":{\"auth\":\"${auth_token_std}\"}}}"
    b64enc "$auths_str"
    return $?
}

registry_auth="$(print_auth "$(mkauth "${username}" "${password}")")"

if [[ "$INSTALL_OPERATOR" == "true" ]]; then
    res=$(
        cat <<EOF
apiVersion: v1
data:
  .dockerconfigjson: ${registry_auth}
kind: Secret
metadata:
  name: quay-ips
  namespace: ${STACKROX_OPERATOR_NAMESPACE}
type: kubernetes.io/dockerconfigjson
EOF
    )
    echo "$res" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
fi

res=$(
    cat <<EOF
apiVersion: v1
data:
  .dockerconfigjson: ${registry_auth}
kind: Secret
metadata:
  name: quay-ips
  namespace: $ACSMS_NAMESPACE
type: kubernetes.io/dockerconfigjson
EOF
)
echo "$res" | $KUBECTL -n "$ACSMS_NAMESPACE" apply -f -
