/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedCentralAllOfSpecEndpointTls struct for ManagedCentralAllOfSpecEndpointTls
type ManagedCentralAllOfSpecEndpointTls struct {
	Cert string `json:"cert,omitempty"`
	Key  string `json:"key,omitempty"`
}
