/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneCentralStatusRoutes struct for DataPlaneCentralStatusRoutes
type DataPlaneCentralStatusRoutes struct {
	Domain string `json:"domain,omitempty"`
	Router string `json:"router,omitempty"`
}
