/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ManagedCentralAllOfSpecAuth struct for ManagedCentralAllOfSpecAuth
type ManagedCentralAllOfSpecAuth struct {
	ClientSecret string `json:"clientSecret,omitempty"`
	ClientId     string `json:"clientId,omitempty"`
	OwnerUserId  string `json:"ownerUserId,omitempty"`
	OwnerOrgId   string `json:"ownerOrgId,omitempty"`
	Issuer       string `json:"issuer,omitempty"`
}
