/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneClusterUpdateStatusRequestCentralOperator struct for DataPlaneClusterUpdateStatusRequestCentralOperator
type DataPlaneClusterUpdateStatusRequestCentralOperator struct {
	Ready           bool     `json:"ready"`
	Version         string   `json:"version"`
	CentralVersions []string `json:"centralVersions,omitempty"`
}
