// Package constants ...
package constants

// CentralOperatorNamespace ...
const CentralOperatorNamespace = "redhat-managed-central-operator"

// FleetShardOperatorNamespace ...
const FleetShardOperatorNamespace = "redhat-fleetshard-operator"
